<script lang="ts">
	import Fa from 'svelte-fa';
	import { faHeart, faNetworkWired } from '@fortawesome/free-solid-svg-icons';

	import type { PageData } from './$types';

	export let data: PageData;
	export let error: unknown;

	let { komputer, user } = data;
</script>

{#if error}
	<p>Error: {error}</p>
{:else if data}
	<h1>Data generated by ssr loaded successfully!</h1>
	<div class="container my-12 mx-auto px-4 md:px-12">
		<div class="flex flex-wrap -mx-1 lg:-mx-4">
			{#each komputer as item}
				<div
					class="my-1 px-1 w-full md:w-1/2 lg:my-4 lg:px-4 lg:w-1/3"
					style={item['status'] == 'waiting' ? 'border-color: red' : 'border-color: green'}
				>
					<article
						class="overflow-hidden rounded-lg shadow-lg {item['dynamic'] == 'true'
							? 'bg-gray-200'
							: 'bg-inherit'}"
					>
						<header class="flex items-center justify-between leading-none p-2 md:p-4">
							<a class="flex items-center no-underline hover:underline text-black" href="#">
								<img
									alt="Placeholder"
									class="block rounded-full"
									src="https://picsum.photos/32/32/?random"
								/>
								<p class="ml-2 text-sm">{item['host-name']}</p>
							</a>
							<div
								class="flex space-x-2 items-center justify-center {item['status'] == 'waiting'
									? 'text-red-500'
									: 'text-green-500'} "
							>
								<p>
									{#if item['status'] == 'waiting'}
										putus
									{:else}
										terhubung
									{/if}
								</p>
								<Fa icon={faNetworkWired} />
							</div>
						</header>
						<div class="space-y-2 py-2">
							<div class="flex px-2">
								<button
									type="button"
									disabled
									class="w-full text-white bg-gray-600 hover:bg-gray-700 focus:outline-none focus:ring-4 focus:ring-gray-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-gray-600 dark:hover:bg-gray-700 dark:focus:ring-gray-700 dark:border-gray-700"
									>Mati</button
								>
								<button
									type="button"
									class="w-full text-gray-900 bg-white border border-gray-300 focus:outline-none hover:bg-gray-100 focus:ring-4 focus:ring-gray-100 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-gray-800 dark:text-white dark:border-gray-600 dark:hover:bg-gray-700 dark:hover:border-gray-600 dark:focus:ring-gray-700"
									>Nyala</button
								>
							</div>
							<ul class="px-4">
								<li>mac: {item['active-mac-address']}</li>
								<li>
									address: <input
										type="text"
										value={item['active-address']}
										disabled={item['dynamic'] == 'true'}
									/>
								</li>
							</ul>
						</div>
						<a href="#">
							<img
								alt="Placeholder"
								class="block h-auto w-full"
								src="https://picsum.photos/600/400/?random"
							/>
						</a>
						<footer class="flex items-center justify-between leading-tight p-2 md:p-4">
							<p class="text-md">
								pengguna: {user?.filter((obj) => obj['address'] == '10.10.10.49')[0]['user'] ?? ''}
							</p>
							<p class="text-grey-darker text-sm">
								uptime: {user?.filter((obj) => obj['address'] == '10.10.10.49')[0]['uptime'] ?? ''}
							</p>
						</footer>
					</article>
				</div>
			{/each}
		</div>
	</div>
{:else}
	<p>Loading...</p>
{/if}
